name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: 'http://localhost:3000'

      # in each pull request, compare current code coverage
      # against the code coverage badge in README file
      # Tip: if you really want to change code coverage
      # you can edit that badge ...
      - name: Set code coverage commit status 📫
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: github.event_name == 'pull_request'
        run: npx set-gh-status --check-against-readme
        env:
          # show debug logs from "set-gh-status" script
          DEBUG: check-code-coverage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # if running on master branch, update the README code coverage badge
      - name: Update code coverage badge 🥇
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#push-event-push
        if: github.event_name == 'push' && github.ref == 'master'
        run: npx update-badge

      # commit any changed files (like README with updated badge)
      # if running on master branch
      # https://github.com/mikeal/publish-to-github-action
      - uses: mikeal/publish-to-github-action@master
        if: github.event_name == 'push' && github.ref == 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
