name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: 'http://localhost:3000'

      # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
      - name: Set code coverage commit status 📫
        if: github.event_name == 'pull_request'
        run: npx set-gh-status --check-against-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://help.github.com/en/actions/reference/events-that-trigger-workflows#push-event-push
      - name: Update code coverage badge 🥇
        if: github.event_name == 'push' && github.ref == 'master'
        run: npx update-badge

      # commit any changed files
      # https://github.com/mikeal/publish-to-github-action
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
